### ISSUE TITLE
[bug] AttributeError: 'Namespace' object has no attribute 'targets_file'

### ISSUE THREAD

**Issue by p0dalirius** [p0dalirius/RDWArecon#2]
```
        ____  ____ _       _____                             
       / __ \/ __ \ |     / /   |  ________  _________  ____ 
      / /_/ / / / / | /| / / /| | / ___/ _ \/ ___/ __ \/ __ \   @podalirius_
     / _, _/ /_/ /| |/ |/ / ___ |/ /  /  __/ /__/ /_/ / / / /   
    /_/ |_/_____/ |__/|__/_/  |_/_/   \___/\___/\____/_/ /_/    v1.2
                                                             
    
Traceback (most recent call last):
  File "/workspace/tools/RDWARecon/./RDWArecon.py", line 173, in <module>
    options = parseArgs()
              ^^^^^^^^^^^
  File "/workspace/tools/RDWARecon/./RDWArecon.py", line 40, in parseArgs
    if (args.targets_file is None) and (len(args.target) == 0):
        ^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'targets_file'
```

**Comment by p0dalirius** [comment]
fixed.
